version: '3.9'

services:
  api:
    container_name: taller_jwt
    image: api-rest-django
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    expose:
      - 8000
    command: python manage.py runserver 0.0.0.0:8000

networks:
  default:
    name: development
    external: true